# Generated by Django 2.0.3 on 2018-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maildata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_data', models.CharField(max_length=50)),
                ('reciver_data', models.CharField(max_length=50)),
                ('subject_data', models.CharField(max_length=50)),
                ('message_data', models.CharField(max_length=100)),
            ],
        ),
    ]
