# Generated by Django 2.0.3 on 2018-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlist', models.EmailField(max_length=254)),
            ],
        ),
    ]
