# Generated by Django 2.0.3 on 2018-04-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='elist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_recorder.cat')),
            ],
        ),
        migrations.CreateModel(
            name='email',
            fields=[
                ('usr_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='usr_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_recorder.email'),
        ),
    ]
