# Generated by Django 2.0.3 on 2018-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_recorder', '0003_auto_20180417_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='elist',
            name='heavylist',
            field=models.CharField(default='none by admin', max_length=100),
        ),
    ]
