# Generated by Django 2.0.3 on 2018-04-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_recorder', '0005_auto_20180417_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststore',
            name='email',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.CASCADE, to='email_recorder.email'),
        ),
    ]
