# Generated by Django 2.0.3 on 2018-04-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_recorder', '0006_liststore_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liststore',
            name='email',
        ),
    ]
