# Generated by Django 2.0.3 on 2018-03-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_ebooks',
            name='image',
        ),
    ]
