# Generated by Django 2.0.3 on 2018-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0002_remove_add_ebooks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_ebooks',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
