# Generated by Django 2.0.3 on 2018-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0003_auto_20180319_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ebooks',
            name='image',
            field=models.ImageField(default='no pic', upload_to='media/'),
        ),
    ]
