# Generated by Django 2.0.3 on 2018-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0004_add_ebooks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='no pic', upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='add_ebooks',
        ),
    ]
