# Generated by Django 2.0.3 on 2018-03-24 17:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0005_auto_20180324_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ebook',
            name='ebook_download',
            field=models.FileField(default='no file', storage=django.core.files.storage.FileSystemStorage(location='F:\\major_project\\mp\\ondemandservices\\media'), upload_to='media/'),
        ),
    ]
