# Generated by Django 2.0.3 on 2018-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_ebooks', '0006_add_ebook_ebook_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ebook',
            name='user_name',
            field=models.CharField(default='anaonymous_user', max_length=50),
        ),
    ]
